### ISSUE TITLE
Items to-do 30mins - 1hr before tutorial

### ISSUE THREAD

**Issue by pavithraes** [nebari-dev/presentations#42]
For @dharhas 

- [x] Execute all cells (in the main notebook set or a side-set) to have displayed output if computes take time
- [ ] TBD
- [ ] 

For @pavithraes or @iameskild:

- [x] Request+release ~1600 machines to warm them up for Dask workflows
- [x] Login to Jitsi chat
- [ ] TBD

**Comment by pavithraes** [comment]
Complete!
